import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Background from "@/components/Background";

export const metadata: Metadata = {
  title: "MicaheDev - Portfolio",
  description: "Generated by create next app",
  icons: "/logo.svg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="border-4 border-black max-w-screen-2xl mx-auto font-departure-mono text-base max-md:text-sm">
          <Background/>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
